
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author P0068839
 */

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.FileNotFoundException;
import java.util.Scanner;

public class MainJFrame extends javax.swing.JFrame {
    
    // ATTRIBUTES
    public MyHashTable theHT;
    
    
    // CONSTRUCTORS
    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        
        theHT = new MyHashTable(10);
        System.out.println("HERE HERE");
        
    }
    
    
    // METHODS   
    
    public MyHashTable getTheHT() {
        return theHT;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        label1 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton2.setText("Display number of employees");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Add new employee");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pressed_jButton3(evt);
            }
        });

        jButton5.setText("Search/edit/delete");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pressed_jButton5(evt);
            }
        });

        jButton6.setText("Load from file (will overwrite current data!)");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pressed_jButton6(evt);
            }
        });

        jButton7.setText("Save to file");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pressed_jButton7(evt);
            }
        });

        label1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        label1.setText("Marcus's EMS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6)
                    .addComponent(jButton5)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton7))
                .addContainerGap(301, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addGap(31, 31, 31)
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        SeparateJFrame theSeparateJFrame = new SeparateJFrame();
        theSeparateJFrame.setVisible(true);
        //MyHashTable refVal = getTheHT();
        //MyHashTable refVal = theHT;
        theSeparateJFrame.setMainHT(theHT);  // Have theSeparateJFrame mainHT point to the real HT.
    }//GEN-LAST:event_jButton2ActionPerformed

    private void pressed_jButton3(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pressed_jButton3
        // TODO add your handling code here:
        AddNewEmployeeJFrame theANEJFrame = new AddNewEmployeeJFrame();
        theANEJFrame.setVisible(true);
        MyHashTable refVal = getTheHT();
        theANEJFrame.setMainHT(refVal);
    }//GEN-LAST:event_pressed_jButton3

    private void pressed_jButton5(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pressed_jButton5
        // TODO add your handling code here:
        SearchEditJFrame theSEJFrame = new SearchEditJFrame();
        theSEJFrame.setVisible(true);
        MyHashTable refVal = getTheHT();
        theSEJFrame.setMainHT(refVal);
    }//GEN-LAST:event_pressed_jButton5

    private void pressed_jButton6(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pressed_jButton6
        // TODO add your handling code here:
        // remember to clear the entire hash table
        for(int i = 0; i < theHT.buckets.length; i++) {
            theHT.buckets[i].clear();
        }
        theHT.numInHashTable = 0;
        
        // https://www.w3schools.com/java/java_files_read.asp
        try {
          File f = new File("file.txt");
          Scanner myReader = new Scanner(f);
          while (myReader.hasNextLine()) {
            String data = myReader.nextLine();
            String[] arr = data.split(",");
            if(arr[0] == "PTE") {
                PTE emp = new PTE(Integer.parseInt(arr[1]), arr[2], arr[3], Integer.parseInt(arr[4]), 
                        arr[5], Double.parseDouble(arr[6]), Double.parseDouble(arr[7]), Double.parseDouble(arr[8]), Double.parseDouble(arr[9]));
                theHT.addEmployee(emp);
            } else {
                FTE emp = new FTE(Integer.parseInt(arr[1]), arr[2], arr[3], Integer.parseInt(arr[4]), 
                        arr[5], Double.parseDouble(arr[6]), Double.parseDouble(arr[7]));
                theHT.addEmployee(emp);
            }     
          }
          myReader.close();
        } catch (FileNotFoundException e) {
          System.out.println("An error occurred.");
          e.printStackTrace();
        }
    }//GEN-LAST:event_pressed_jButton6

    private void pressed_jButton7(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pressed_jButton7
        // TODO add your handling code here:
        System.out.println("Saving to file");
        // source: https://www.w3schools.com/java/java_files_create.asp
        try {
            File f = new File("file.txt");
            if (f.createNewFile()) {
              System.out.println("File created: " + f.getName());
            } else {
              System.out.println("File already exists.");
            }
            
            FileWriter writer = new FileWriter("file.txt");
            for(int i = 0; i < theHT.buckets.length; i++) {
                for(EmployeeInfo e: theHT.buckets[i]) {
                    System.out.println(e);
                    if(e instanceof PTE) {
                       String out = "PTE";
                       out += ","+e.getEmpNum();
                       out += ","+e.getFirstName();
                       out += ","+e.getLastName();
                       out += ","+e.getGender();
                       out += ","+e.getWorkLocation();
                       out += ","+e.getDeductionRate();
                       out += ","+e.getHourlyWage();
                       out += ","+e.getHoursPerWeek();
                       out += ","+e.getWeeksPerYear();
                       writer.write(out + "\n");
                    } else {
                       String out = "FTE";
                       out += ","+e.getEmpNum();
                       out += ","+e.getFirstName();
                       out += ","+e.getLastName();
                       out += ","+e.getGender();
                       out += ","+e.getWorkLocation();
                       out += ","+e.getDeductionRate();
                       out += ","+e.getYearlySalary();
                       writer.write(out + "\n");
                    }
                }
            }
//            writer.write("asdf\n");
//            writer.write("line 2");
            writer.close();
          } catch (IOException e) {
            System.out.println("An error occurred.");
            e.printStackTrace();
        }
    }//GEN-LAST:event_pressed_jButton7

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
